version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # Add any other environment variables as needed

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    # Add any other environment variables as needed
